id: '57f91526-e358-4d08-84e5-c18931948b84'
name: 'Require MFA Enrollment'
description: 'Requires that any user not already enrolled in MFA will be presented with an enrollment prompt on their next login.'
public: true
triggers: ['POST_LOGIN']
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/mfa-require-enrollment-POST_LOGIN'
notes: |
    # Notes
     This action requires that any user not already enrolled in MFA will be presented with an
     enrollment prompt on their next login.

     This action can be paired with the Adaptive MFA feature that prompts for an MFA challenge only
     when the login confidence is low. It can also be combined with another custom action that prompts
     for an MFA challenge under a custom condition.

     Use of the Adaptive MFA feature requires an add-on for the Enterprise plan. Please contact sales
     with any questions. See our Adaptive MFA documentation at https://auth0.com/docs/mfa/adaptive-mfa
     for more information.
useCases:
    - 'MULTIFACTOR'
