id: 'dab805d5-aa6c-4e44-abd8-d59d5ddb3c78'
name: 'Roles from a SOAP Service'
description: 'Shows how to query a basic profile http binding SOAP web service for roles.'
public: true
triggers:
    - 'POST_CHANGE_PASSWORD'
runtime: 'node18'
modules:
    - name: '@xmldom/xmldom'
      version: 'latest'
    - name: 'xpath'
      version: 'latest'
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/soap-webservice-POST_CHANGE_PASSWORD'
notes: |
    **Required Secrets**

    * `DOMAIN` - domain name of your SOAP server, eg. my-soap-server.com
    * `SOAP_ACTION` - `SOAPAction` header for the soap request.

useCases:
    - 'ENRICH_PROFILE'
