id: 'f637671e-bf17-4563-bbcc-3d06850e685b'
name: 'Only allow access from a specific IP address'
description: 'Only allow access from a specific IP address'
public: true
triggers:
    - 'PASSWORD_RESET_POST_CHALLENGE'
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/ip-address-allowlist-PASSWORD_RESET_POST_CHALLENGE'
useCases:
    - 'ACCESS_CONTROL'
notes: |
    **Secrets**

    * `ALLOW_LIST` - comma-delimited list of allowed IP addresses.
