id: '5396a2bb-6b32-41d4-b8e1-450f9b3c2f4c'
name: 'Add Persistent Attributes to the User'
description: 'Set any preference value to a user (using `user_metadata`).'
triggers:
    - 'SEND_PHONE_MESSAGE'
runtime: 'node18'
modules:
    - name: 'auth0'
      version: 'latest'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/add-persistence-attribute-SEND_PHONE_MESSAGE'
notes: |
    **Required Secrets**

    * `METADATA_KEY` - key to be used to store the user preference, for example: 'favorite_color'
    * `METADATA_DEFAULT_VALUE` - value to be stored for the user preference in the event that it does not already exist, for example: 'blue'
    * `CLIENT_ID` - client id for an application that is permitted to update your users
    * `CLIENT_SECRET` - corresponding client secret for `CLIENT_ID`, you'll find this in the settings alongside `CLIENT_ID`
    * `TENANT_DOMAIN` - corresponding tenant domain for `CLIENT_ID`, you'll find this in the settings alongside `CLIENT_ID`

useCases:
    - 'ENRICH_PROFILE'
