id: 'c8d3367c-dcdb-41e1-a303-4063d2a1d124'
name: 'Add country to User Profile'
description: "This action template adds a `country` attribute to the user's id token based on their ip address."
public: true
triggers:
    - 'POST_LOGIN'
runtime: 'node18'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/add-country-POST_LOGIN'
notes: |
    **Optional Secrets**

    * `ID_TOKEN_NAMESPACE` - An optional namespace for the custom claim

useCases:
    - 'ENRICH_PROFILE'
