id: '85e0b92c-c4e6-4f26-bb98-bf5f41423b93'
name: 'SAML Configuration'
description: 'Programatically add fields to your SAML configuration.'
public: true
triggers:
    - 'POST_LOGIN'
runtime: 'node18'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/saml-configuration-POST_LOGIN'
notes: |
    **Secrets**

    * `CLIENT_ID` - the client ID of your IDP
    * `SAML_AUD` - the audience, for example `urn:auth0:{yourTenant}:{yourConnectionName}`
    * `SAML_RECIPIENT` - the recipient, for example `https://{yourTenant}.us.auth0.com/login/callback?connection={yourConnectionName}
    * `SAML_DESTINATION` - the destination, for example `https://{yourTenant}.us.auth0.com/login/callback?connection={yourConnectionName}
    * `SAML_LIFETIME_SEC` - the expiration in seconds

    **Notes**

    * Requires a tenant configured as an IdP with the SAML Addon.
      * For more information see [Test SAML SSO with Auth0 as Service Provider and Identity Provider](https://auth0.com/docs/authenticate/protocols/saml/saml-configuration/configure-auth0-as-service-and-identity-provider)
    * Requires sound and valid values for your audience, recipient, destination and lifetime.
      * For more information see [this documentation page](https://auth0.com/docs/saml-configuration#configuration-options)

useCases:
    - 'ENRICH_PROFILE'
