id: 'a3a3caf7-4d96-439a-b5dd-1069c4ad0eed'
name: 'Simple User Allowlist'
description: 'Only allow access to a specific list of users'
public: true
triggers:
    - 'PASSWORD_RESET_POST_CHALLENGE'
runtime: 'node18'
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/simple-user-allowlist-PASSWORD_RESET_POST_CHALLENGE'
notes: |
    **Requird Secrets**

    * ALLOWED_USER_EMAILS - comma separated list of allowed user emails

useCases:
    - 'ACCESS_CONTROL'
