id: '45c70d47-761c-4b78-9c80-17ff347dc1ce'
name: 'Show how to check for variables in the querystring'
description: 'Checks if the login transaction includes a query variable from the QUERY_KEY secret matching a value set in the QUERY_VALUE secret and if it does, it will add an attribute named by the value of EXAMPLE_CUSTOM_CLAIM_NAME and a value of EXAMPLE_CUSTOM_CLAIM_VALUE to the user profile.'
public: true
triggers: ['POST_LOGIN']
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/querystring-POST_LOGIN'
useCases:
    - 'ENRICH_PROFILE'
notes: |
    **Secrets**

    * `QUERY_KEY` - the query parameter name that will be evaluated to set the custom claim
    * `QUERY_VALUE` - the query parameter value that must be matched to set the custom claim
    * `CUSTOM_CLAIM_NAME` - the custom claim name
    * `CUSTOM_CLAIM_VALUE` - the custom claim value
