blank_issues_enabled: false
contact_links:
    - name: Auth0 Community
      url: https://community.auth0.com
      about: Discuss this issue in the Auth0 Community forums
    - name: Actions Templates Documentation
      url: https://auth0.com/docs/customize/actions/actions-templates
      about: Read the actions templates docs
