id: '36e0c077-bf8c-4350-9f6a-85fd90c5ace1'
name: 'Roles from a SOAP Service'
description: 'Shows how to query a basic profile http binding SOAP web service for roles.'
public: true
triggers:
    - 'POST_LOGIN'
runtime: 'node18'
modules:
    - name: '@xmldom/xmldom'
      version: 'latest'
    - name: 'xpath'
      version: 'latest'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/soap-webservice-POST_LOGIN'
notes: |
    **Requied Secrets**

    * `DOMAIN` - domain name of your SOAP server, eg. my-soap-server.com
    * `SOAP_ACTION` - `SOAPAction` header for the soap request.

    **Optional Secrets**

    * `ID_TOKEN_NAMESPACE` - optional namespace for the id token field where the roles will be saved, eg. https://my-domain.com

useCases:
    - 'ENRICH_PROFILE'
