id: '06975b69-6433-4918-98a1-3779f084b21d'
name: 'Add an attribute to the user'
description: 'Add an attribute to the user only for the login transaction. This is useful for cases where you want to enrich the user information for a specific application.'
public: true
triggers: ['POST_LOGIN']
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/add-attribute-POST_LOGIN'
useCases:
    - 'ENRICH_PROFILE'
notes: |
    **Secrets**

    * `CONNECTION_NAME` - the name of the connection from which users will have a custom claim added. For example, `Username-Password-Authentication`.
    * `CLAIM_NAME` - the name of the custom claim to be added.
