id: '0ec391ed-9eb5-4eba-99b6-a054f1aefbfa'
name: 'Show how to check for variables in the querystring'
description: 'Checks if the password reset transaction includes a query variable from the QUERY_KEY secret matching a value set in the QUERY_VALUE secret'
public: true
triggers: ['PASSWORD_RESET_POST_CHALLENGE']
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/querystring-PASSWORD_RESET_POST_CHALLENGE'
useCases:
    - 'ENRICH_PROFILE'
notes: |
    **Secrets**

    * `QUERY_KEY` - the query parameter name that will be evaluated to invoke custom code
    * `QUERY_VALUE` - the query parameter value that must be matched to invoke custom code
