id: '88e3b384-0aaa-44c8-818f-ee7b195fecc4'
name: 'Roles from a SOAP Service'
description: 'Shows how to query a basic profile http binding SOAP web service for roles.'
public: true
triggers:
    - 'SEND_PHONE_MESSAGE'
runtime: 'node18'
modules:
    - name: '@xmldom/xmldom'
      version: 'latest'
    - name: 'xpath'
      version: 'latest'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/soap-webservice-SEND_PHONE_MESSAGE'
notes: |
    **Required Secrets**

    * `DOMAIN` - domain name of your SOAP server, eg. my-soap-server.com
    * `SOAP_ACTION` - `SOAPAction` header for the soap request.

useCases:
    - 'ENRICH_PROFILE'
