id: 'daeda4e8-8da2-4abb-afb5-ac09df0ebb2a'
name: 'On-behalf-of token exchange for first-party apps'
triggers:
    - 'CUSTOM_TOKEN_EXCHANGE'
useCases:
    - 'ACCESS_CONTROL'
public: true
description: 'Implements RFC 8693 OAuth 2.0 Token Exchange for first-party on-behalf-of flows. Securely exchanges Auth0 access tokens for different API audiences while preserving the original user identity, enabling trusted first-party services to call downstream APIs with delegated authorization and appropriate scopes. Common use cases include resource servers, backend services, and Model Context Protocol (MCP) servers that need to access APIs on behalf of authenticated users.'
version: '1.0.0'
runtime: 'node22'
modules:
    - name: 'jose'
      version: '6.1.0'
    - name: 'debug'
      version: '4.4.3'
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/first-party-on-behalf-of-CUSTOM_TOKEN_EXCHANGE'
notes: |
    **Required Secrets**

    - `SUBJECT_TOKEN_AUDIENCE` - Expected audience of incoming tokens (e.g., "https://api.example.com")
    - `ALLOWED_CLIENT_IDS` - JSON array of authorized client IDs (e.g., ["abc123"])
    - `ALLOWED_TARGET_AUDIENCES` - JSON array of permitted API identifiers (e.g., ["https://api.example.com"])
    - `ALLOWED_SCOPES` - JSON array of allowed scopes (e.g., ["openid", "read:data"])

    **Optional Secrets**

    - `DEBUG` - Enable debug logging (e.g., "token-exchange:*" for all logs, "token-exchange:error" for errors only)

    **How to Configure**

    1. Create your Custom Token Exchange Profile via Management API with a unique `subject_token_type`
    2. Configure the required secrets in Dashboard > Actions > Library > [This Action] > Secrets
    3. Use JSON array format for ALLOWED_CLIENT_IDS, ALLOWED_TARGET_AUDIENCES, and ALLOWED_SCOPES
    4. Deploy and attach to Custom Token Exchange flow

    **First party confidential clients only. Scopes are not mapped or passed through from the subject token; requested scopes must be a subset of ALLOWED_SCOPES.**

    **Note:** This template validates Auth0 access tokens issued by this tenant. The `subject_token_type` is configured in the CTE profile and validated by the platform before the Action is invoked.

    See: https://auth0.com/docs/authenticate/custom-token-exchange
