id: 'dd3e7967-33b2-4b55-845b-de24ae7989aa'
name: 'Only allow access from a specific IP address'
description: 'Only allow access from a specific IP address'
public: true
triggers:
    - 'PRE_USER_REGISTRATION'
runtime: 'node18'
secrets:
    - label: 'ALLOW_LIST'
      defaultValue: 'ALLOWED,IP,ADDRESSES'
modules: []
sourceUrl: 'https://github.com/auth0/opensource-marketplace/blob/main/templates/ip-address-allowlist-PRE_USER_REGISTRATION'
useCases:
    - 'ACCESS_CONTROL'
