id: '5b524ee4-1d82-4671-811c-5bea1f3eede3'
name: 'Set roles to a user'
description: 'Add roles to a user based on an arbitrary pattern.'
public: true
triggers:
    - 'POST_LOGIN'
useCases:
    - 'ACCESS_CONTROL'
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/role-creation-POST_LOGIN'
notes: |
    **Secrets**

    * `SPECIAL_ROLE_NAME` - the name of the special role claim.
    * `SPECIAL_ROLE_VALUE` - comma-delimited list of special roles
    * `SPECIAL_ROLE_USERS` - comma-delimited list of users who should be assigned the special role claim

    **Notes**

    * Custom claims must be named appropriately.
      * For more information on restrictions, please see [General restrictions](https://auth0.com/docs/secure/tokens/json-web-tokens/create-custom-claims#general-restrictions)
