id: '365115c1-c962-4769-a6c5-851c4494cc0d'
name: 'Require MFA once per session'
description: 'Avoid prompting a user for multifactor authentication if they have successfully completed MFA in their current session. This is particularly useful when performing silent authentication (`prompt=none`) to renew short-lived access tokens in a SPA (Single Page Application) during the duration of a user session without having to rely on setting `allowRememberBrowser` to `true`.'
public: true
triggers:
    - 'POST_LOGIN'
runtime: 'node18'
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/require-mfa-once-per-session-POST_LOGIN'
notes: |
    # Notes
    * This action code requires at least one factor to be enabled for your tenant.
      * For more information please see [Enable Multi-Factor Authentication](https://auth0.com/docs/secure/multi-factor-authentication/enable-mfa).

useCases:
    - 'MULTIFACTOR'
