id: 'c9fa1544-b8bd-4211-950e-'
name: 'Check if a user belongs to an active directory group.'
description: false
public: true
triggers:
    - 'PASSWORD_RESET_POST_CHALLENGE'
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/active-directory-groups-PASSWORD_RESET_POST_CHALLENGE'
notes: |
    **Secrets**

    * `ALLOWED_GROUP` - the name of the allowed group.
useCases:
    - 'ACCESS_CONTROL'
