id: '557d5c47-54ff-46e4-b082-765f0c3f5cbc'
name: 'Simple Domain Allow List'
description: 'This actions template will only allow access for users with specific email domains.'
public: true
triggers:
    - 'POST_LOGIN'
runtime: 'node18'
modules: []
sourceUrl: 'https://github.com/auth0/os-marketplace/blob/main/templates/simple-domain-allowlist-POST_LOGIN'
useCases:
    - 'ACCESS_CONTROL'
notes: |
    **Secrets**

    * `ALLOWED_DOMAINS` - comma delimited list of email domains users are allowed to use.
